---
- hosts: Ansible01
  become: true

  tasks:

  - name: Remove User
    user:
      name: MarkMcLean
      state: absent

  - name: Remove User Home Directory
    file:
      path: /home/MarkMcLean
      state: absent
  ...
