---
- name: Push ansible user info
  hosts: client1_l00155876 

  tasks:

  - name: create my admin user
    user:
     name: "Mark McLean"
     comment: "My admin user Managment Project"
     group: admin
      

