---
- name: Create Ansible01 Linux User
  hosts: Ansible01
  become: true
  vars_files: 
        - /etc/ansible/vars_files/pwd_mark.yaml

  tasks:

    - name: Add group SYSAdmin to Ansible01 server
      group:
        name: SYSAdmin
        gid: 2010
        state: present

    - name: "Add user MarkMcLean to Ansible01"
      user:
        name: MarkMcLean
        password: "{{ pwd_mark | password_hash('sha512') }}"
        comment: MarkMcLean
        uid: 2001
        group: SYSAdmin"      
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/MarkMcLean
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
...
