---
- name: "Create Linux User"
  hosts: client1_l00155876 
  become: "true"
  vars:
    users:
    - username: "MarkMcLean"
    - groups: "admin"
    - state: "present"
    - shell: "/bin/bash"
    - system: "no"
    - createhome: "yes"
    - home: "/home/MarkMcLean"
    - username: "Test"
      groups: "admin"
    remove_users:
    - username: "l00155876"
    
  tasks:

  - name: "create my linux account"
    user:
     name: "MarkMcLean"
     password: "College2020!"
     comment: "My admin user Managment Project"
     group: "sudo"
     state: "present"
     password: "$6$JLzGbGyK$XYiwL6VPqvImSmnPrCZW0Z673Gk/mmUQJBC5nCHVFAbEj/x9Pp/76aNJI0wOewKOpQJIGmC0BRp/8/J4u5/tC/"
     shell: /bin/bash
     system: no
     createhome: yes
     home: /home/MarkMcLean
     
  - name: "Remove User"
    user:
      name: "{{ item }}"
      state: "absent"
    with_items: "{{ remove_users }}"
