---
- name: "Create Remote Linux User"
  hosts: "client1_l00155876"
  become: "true"
  vars_files: 
        - /etc/ansible/vars_files/pwd_mark.yaml

  tasks: 

    - name: Add group SYSAdmin to remote server
      group:
        name: SYSAdmin
        gid: 2010
        state: present


    - name: Add user MarkMcLean to remote server
      user:
        name: MarkMcLean
        password: "{{ pwd_mark | password_hash('sha512') }}"
        comment: MarkMcLean
        uid: 2001
        group: SYSAdmin
        append: yes
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/MarkMcLean

    - authorized_key:
        user: MarkMcLean
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/home/l00155876/.ssh/id_rsa.pub') }}"

    - name: "Allow admin users to sudo without a password"
      lineinfile:
       path: /etc/sudoers
       state: present
       regexp: ^%sudo
       insertafter: "^%sudo ALL=(ALL) NOPASSWD: ALL"
       line: "MarkMcLean ALL=(ALL) NOPASSWD: ALL"

    - name: Allow authorised keys
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no

    - name: Disable Password Autentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: ^AuthorizedKeysFile
        line: AuthorizedKeysFile      %h/.ssh/authorized_keys
